# Generated by Django 5.2.6 on 2026-03-04 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='subject start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='subject end')),
                ('informed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='grade')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='EvalDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='evaluation start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='evaluation end')),
                ('informed', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('informed', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(through='evaluations.SubjectStudent', to='evaluations.student'),
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('eval_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaldesign')),
                ('subject_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.subjectstudent')),
            ],
        ),
        migrations.AddField(
            model_name='evaldesign',
            name='subject_students',
            field=models.ManyToManyField(through='evaluations.EvalResult', to='evaluations.subjectstudent', verbose_name='Estudiantes inscritos'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.teacher'),
        ),
        migrations.AddConstraint(
            model_name='subjectstudent',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='unique_subject_student'),
        ),
        migrations.AddConstraint(
            model_name='evalresult',
            constraint=models.UniqueConstraint(fields=('subject_student', 'eval_design'), name='unique_subject_student_eval_design'),
        ),
    ]
