# Generated by Django 5.2.15 on 2026-06-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "assessments_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON for filtering assessments to fetch.",
                    ),
                ),
                (
                    "evaluations_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON for filtering evaluations to fetch (not implemented yet).",
                    ),
                ),
                (
                    "attendance_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON for filtering attendance to fetch (not implemented yet).",
                    ),
                ),
                (
                    "css_content",
                    models.TextField(
                        blank=True,
                        help_text="Enter raw CSS that would be wrapped in style block.",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True,
                        help_text="Enter raw HTML that would be wrapped in an article block.",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(blank=True, null=True, upload_to="logos"),
                ),
            ],
        ),
    ]
