# Generated by Django 5.2 on 2026-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_customreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='main_teachers',
            field=models.ManyToManyField(blank=True, to='evaluations.teacher'),
        ),
    ]
