# Generated by Django 5.2.15 on 2026-06-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradeScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RubricDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rank", models.SmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="stlogs.rubric",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("rank", models.SmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "grade_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="stlogs.gradescheme",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="stlogs.rubric",
                    ),
                ),
                (
                    "rubric_domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criteria",
                        to="stlogs.rubricdomain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.CharField(blank=True, max_length=40)),
                ("rank", models.SmallIntegerField()),
                (
                    "grade_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_options",
                        to="stlogs.gradescheme",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grade_scheme", "rank"),
                        name="unique_grade_scheme_rank_combination",
                        violation_error_message="This rank already exists in the grading scheme.",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rubricdomain",
            constraint=models.UniqueConstraint(
                fields=("rubric", "rank"),
                name="unique_rubric_rank_combination_in_domains",
                violation_error_message="This rank already exists in the rubric.",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubriccriterion",
            constraint=models.UniqueConstraint(
                fields=("rubric", "rank"),
                name="unique_rubric_rank_combination_in_criteria",
                violation_error_message="This rank already exists in the rubric.",
            ),
        ),
    ]
