# Generated by Django 5.2.15 on 2026-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stlogs", "0002_studentassessment_criterionscore"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="criterionscore",
            constraint=models.UniqueConstraint(
                fields=("student_assessment", "rubric_criterion"),
                name="unique_student_assessment_rubric_criterion_combination",
                violation_error_message="This criterion already exists in this assessment.",
            ),
        ),
    ]
