# Generated by Django 5.2.6 on 2026-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('late_time', models.TimeField(blank=True, null=True)),
                ('retire_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('activity_type', models.PositiveSmallIntegerField(choices=[(1, 'Común'), (2, 'Salida'), (3, 'Encuentro'), (4, 'Paseo')], default=1)),
            ],
        ),
    ]
