# Generated by Django 5.2.6 on 2026-03-04 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.student'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='students',
            field=models.ManyToManyField(through='attendance.Attendance', to='evaluations.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolactivity'),
        ),
        migrations.AddConstraint(
            model_name='schoolactivity',
            constraint=models.CheckConstraint(condition=models.Q(('end__date', models.F('start__date')), ('end__date', None), _connector='OR'), name='activity_start_and_end_on_same_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_student'),
        ),
    ]
